# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET 9 Core sdk'
  inputs:
    packageType: 'sdk'
    version: '9.x'
    performMultiLevelLookup: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestStable'

- task: VSTest@3
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2:
      '.\KeepAChangelogParser.Tests\bin\Debug\net9.0\KeepAChangelogParser.Tests.dll'
      #'**\KeepAChangelogParser.Tests.dll'
    vstestLocationMethod: 'version'
    vsTestVersion: 'toolsInstaller'
    runInParallel: true
    codeCoverageEnabled:  true
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
